<a href="https://colab.research.google.com/github/mnshcodie/IIScEx_2021/blob/main/DLFA_B1_M0_SNB_Practice_01_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification Program in DLFA
##  A program by IISc and TalentSprint

### Practice Notebook 1: Introduction to NumPy(Ungraded)


## Learning Objectives

At the end of the experiment, you will be able to :

* understand the basics of NumPy including its functional objects
* describe the key characteristics of numpy arrays
* understand the difference between Python list and NumPy arrays
* use indexing to slice/select data from NumPy arrays



## Information

#### NumPy

* NumPy stands for 'Numerical Python'
* It is a package for data analysis and scientific computing with Python
* At the heart of NumPy is a basic data type, called the NumPy array. A NumPy array may have a number of dimensions, thus allowing it to represent quantities such as vectors (1D), matrices (2D), or higher dimensional arrays such as tensors.
* It offers ndarray data structure for storing and ufuncs for efficiently processing the (homogeneous) data. Some of the important functionalities include: basic slicing, advanced or fancy indexing, broadcasting, etc.

**To know more about Numpy click [here](https://numpy.org/doc/stable/user/whatisnumpy.html)**


#### Difference Between Python list and NumPy array

* Python lists are very general. They can contain any kind of object. They are dynamically typed.
* They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).

**To know more about the differece between Python list and NumPy arrays click [here](https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference#:~:text=A%20numpy%20array%20is%20a,a%20tuple%20of%20nonnegative%20integers.&text=A%20list%20is%20the%20Python,contain%20elements%20of%20different%20types.)**

## Expected time to complete the experiment : 20 mins

#### Exercise 1: Import the numpy package under the name np

In [ ]:
# Your code here
import numpy as np

#### Exercise 2: Create a one-dimensional array

In [ ]:
# Your code here
A  = np.arange(10)
a  = [1, 2, 3]
np.array(a)
A.shape

(10,)

#### Exercise 3: Create a two-dimensional array

In [ ]:
# Your code here
np.array([[1, 2], [3, 4]])
np.arange(24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#### Exercise 4: Create an array of 10 fives

In [ ]:
# Your code here
np.ones(10) * 5
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Exercise 5: Create an array of 30 zeros


In [ ]:
# Your code here
np.zeros(30).shape

(30,)

#### Exercise 6: Create an array of odd integers from 20 to 40

In [ ]:
 # Your code here
 arr = np.arange(20, 41)
 arr[(arr % 2) != 0]
 
 #np.arange(21, 40, 2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

#### Exercise 7: Create a 5 * 5 identity matrix

In [ ]:
# Your code here
np.identity(5)
np.eye(5, )

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Exercise 8: Generate an array of 20 random numbers sampled from a standard normal distribution

In [ ]:
# Your code here
np.random.standard_normal(20)

array([-1.44653843, -1.47139334,  3.02876697, -0.26921717, -0.90233466,
       -2.07985259, -0.19279923,  1.20597938, -0.01596788, -0.57052936,
       -0.1353644 , -0.91333457,  2.18218633,  1.24894567,  0.51775548,
       -0.41196929,  0.30980538, -0.09641228,  0.87068036, -0.41720052])

#### Exercise 9: Create a numpy array from a List

In [ ]:
# Your code here
l = [1, 2, 3]
np.array(l)
np.array(list(range(20)))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### Exercise 10:  Create a 4 * 4 * 4 array with random values

In [ ]:
# Your code here
np.random.random((4,4,4))
np.random.rand(4,4,4)

array([[[0.66785512, 0.35818052, 0.77138371, 0.1575922 ],
        [0.54330586, 0.38077079, 0.39248595, 0.19699866],
        [0.05783533, 0.16467414, 0.63396561, 0.51325051],
        [0.96521294, 0.62622136, 0.5420164 , 0.22912889]],

       [[0.88891335, 0.15634009, 0.91390192, 0.24002649],
        [0.22259186, 0.64018628, 0.50952844, 0.32740368],
        [0.45846245, 0.86285327, 0.81507448, 0.54449967],
        [0.9693062 , 0.7849179 , 0.93812063, 0.82169925]],

       [[0.69633459, 0.98379458, 0.4998435 , 0.1397118 ],
        [0.14826619, 0.89516384, 0.65508584, 0.12358123],
        [0.78668765, 0.02472477, 0.92330332, 0.84893442],
        [0.10434823, 0.21581432, 0.8379515 , 0.68028506]],

       [[0.21952807, 0.0372761 , 0.9941896 , 0.62771541],
        [0.52571948, 0.898466  , 0.30058408, 0.43569783],
        [0.76811338, 0.54980703, 0.01324103, 0.40797367],
        [0.50795748, 0.64897523, 0.13313631, 0.17373278]]])

#### Exercise 11: Create a 10 * 10 array with random values and find the minimum and maximum values 

In [ ]:
# Your code here

b = np.random.rand(10,10)
b.max(), np.max(b), b.min()


(0.9930969835439335, 0.9930969835439335, 0.0011869484295707888)

#### Exercise 12: Create a checkerboard 8 * 8 matrix using the tile function

In [ ]:
# Your code here
np.tile([[1, 0],[0,1]], (8,8))

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

#### Exercise 13: Given two arrays *A* and *B*, perform the below operations:

* A + B
* A - B
* A * B
* A / B
* A ** 3

A = np.arange(1,6)

B = np.arange(6, 15, 2)

In [ ]:
# Your code here
A = np.arange(1,6)
B = np.arange(6, 15, 2)
print(A, B)

A + B
A - B
A * B
A/B
A ** 3

[1 2 3 4 5] [ 6  8 10 12 14]


array([  1,   8,  27,  64, 125])

#### Exercise 14: Given an array *X*. Calculate sine, cosine, and tangent of *X*, element-wise.

X = np.array([1, 45, 60, 90])

In [ ]:
# Your code here
X = np.array([1, 45, 60, 90])
print(np.sin(X[0]))
# print(np.cos(X))
# np.tan(X)

X[0]

0.8414709848078965


1

#### Exercise 15: Given an array *X*. Convert angles from degrees to radians.

X = np.array([-180.,  -90.,   90.,  180.])

In [ ]:
# Your code here
X = np.array([1, 45, 60, 90])
np.deg2rad(X)

array([0.01745329, 0.78539816, 1.04719755, 1.57079633])

#### Exercise 16: Given an array *X*. Calculate the round, ceil, floor of *X*, element-wise

X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])

In [ ]:
# Your code here
X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])
np.round(X), np.ceil(X), np.floor(X)
# np.round?

(array([  4.,   2.,  44.,  26.,  -1., -10.,  -7.]),
 array([ 5.,  3., 45., 26., -1., -9., -6.]),
 array([  4.,   2.,  44.,  25.,  -2., -10.,  -7.]))

#### Exercise 17: Given two arrays *X* and *Y*. Divide *X* by *Y* element-wise using divide, true_divide, floor_divide functions.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
# Your code here
X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

np.divide(X, Y)
np.true_divide(X, Y)
np.floor_divide(X, Y)

array([0, 0, 0])

#### Exercise 18: Given two arrays *X* and *Y*. Compute $X^Y$, element-wise.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [ ]:
# Your code here

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

X ** Y

np.power(X , Y)

array([  1,  32, 729])

#### Exercise 19:  Given an array *X*. If an element of *X* is smaller than 5, replace it with 4. And if an element of *X* is bigger than 9, replace it with 8.

X = np.array([8, 4, 22, 3, 66, 12, 1, 5])

In [ ]:
# Your code here
X = np.array([8, 4, 6, 3, 66, 12, 1, 5])
np.clip(X, 4, 8)

array([8, 4, 6, 4, 8, 8, 4, 5])

#### Exercise 20: Use the functions len(), numpy.shape() on array *X*. How do they relate to each other? And to the ndim attribute of the arrays?

X = np.array([8, 4, 22, 3, 66, 12, 1, 5])

In [ ]:
# Your code here
X = np.array([8, 4, 22, 3, 66, 12, 1, 5])
len(X), X.ndim, X.shape

(8, 1, (8,))

#### Exercise 21: Create a 2-D array called X, ranging from -1 to 14 using arange() with step size 0.25. Split this array row wise into 3 equal parts and print the result.

In [ ]:
# Your code here
X = np.arange(-1, 14, 0.25)
X1 = X.reshape(3, 20)
X1

array([[-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,
         1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,
         3.5 ,  3.75],
       [ 4.  ,  4.25,  4.5 ,  4.75,  5.  ,  5.25,  5.5 ,  5.75,  6.  ,
         6.25,  6.5 ,  6.75,  7.  ,  7.25,  7.5 ,  7.75,  8.  ,  8.25,
         8.5 ,  8.75],
       [ 9.  ,  9.25,  9.5 ,  9.75, 10.  , 10.25, 10.5 , 10.75, 11.  ,
        11.25, 11.5 , 11.75, 12.  , 12.25, 12.5 , 12.75, 13.  , 13.25,
        13.5 , 13.75]])

#### Exercise 22: Use the array X created above and write the commands for the following: 

* Find the sum of all elements
* Find the sum of all elements row wise
* Find the sum of all elements column wise
* Find the max of all elements
* Find the min of all elements in each row
* Find the mean of all elements in each row
* Find the standard deviation column wise

In [ ]:
# Your code here
print("sum is",np.sum(X1))
print("\nsum of all elements row wise\n",np.sum(X1, axis=0))
print("\nsum of all elements col wise\n",np.sum(X1, axis=1))
print("\nmax and min",X1.max(), X1.min())
print("\n min row wise",np.min(X1, axis=0))
print("\n mean row wise",np.mean(X1, axis=0))
print("\n standard deviation col wise",np.std(X1, axis=1))

sum is 382.5

sum of all elements row wise
 [12.   12.75 13.5  14.25 15.   15.75 16.5  17.25 18.   18.75 19.5  20.25
 21.   21.75 22.5  23.25 24.   24.75 25.5  26.25]

sum of all elements col wise
 [ 27.5 127.5 227.5]

max and min 13.75 -1.0

 min row wise [-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.    1.25  1.5   1.75
  2.    2.25  2.5   2.75  3.    3.25  3.5   3.75]

 mean row wise [4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25
 7.5  7.75 8.   8.25 8.5  8.75]

 standard deviation col wise [1.44157032 1.44157032 1.44157032]
